apiVersion: v2
name: reposilite
version: "1.0.0" # The version of this chart.
appVersion: "3.0.4" # The latest version of Reposilite.
description: "Lightweight and easy-to-use repository management software dedicated for the Maven based artifacts in the JVM ecosystem"
icon: https://github.com/dzikoysk/reposilite/blob/main/reposilite-site/public/images/favicon.png
type: application
keywords: # A list of keywords for Reposilite.
  - reposilite
  - maven
  - gradle
  - sbt
  - deploy
  - artifact-repository-manager
  - repository-manager
sources: # A list of URLs to the source code of Reposilite.
  - https://github.com/dzikoysk/reposilite
maintainers: # A list of Chart maintainers
  - name: dzikoysk
    email: dzikoysk@dzikoysk.net
    url: https://github.com/dzikoysk